baseURL = "phury.github.io/banana-waza/"
languageCode = "fr-be"
title = "Banana Waza"
subtitle = "La véritable source d´information sur le kendo"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = false
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "Serif - A Hugo Business Theme"

  [params.homepage_meta_tags]
    meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_og_title = "Hugo Serif Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 120

  [params.footer]
    copyright_text = 'Copyright © 2020 by Banana Waza Publishing. All rights reserved. Generated by Hugo. Theme <a class="zerostatic" href="https://www.zerostatic.io">Serif</a>.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
      weight = 1

  [[menu.main]]
    name = "Auteurs"
    url = "/authors/"
      weight = 2

#  [[menu.main]]
#      name = "Team"
#      url = "/team/"
#      weight = 2

  [[menu.main]]
      name = "A propos"
      url = "/about/"
      weight = 3

#  [[menu.main]]
#      name = "Contact"
#      url = "/contact/"
#      weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

#  [[menu.footer]]
#    name = "Contact"
#    url = "/contact/"
#      weight = 2
